- name: variables from inventory
  hosts: web
  tasks:
  - name: print the course information #no need to mention anything in the play to access this variables
    ansible.builtin.debug:
     msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"