- name: variables
  hosts: local
  connection: local
  # vars:
  #   GREET: "PLAY"
  vars_files:
  - file-vars.yaml
  # vars_prompt:
  # - name: GREET
  #   prompt: Enter the greet
  #   private: false
  tasks:
    - name: print the variables
      # vars:
      #   GREET: "TASK"
      ansible.builtin.debug:
        msg: "Hello from {{ GREET }}"

# PREFERENCES
#1. Command line
#2. TASK level
#3. Files
#4. Prompt
#5. Play
#6. Inventory