- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle the undefine variable
    ansible.builtin.debug:
      msg: "Hello {{ person | default('Ramesh') }}"

  - name: converting string to list
    vars:
      fruits: banana, apple, orange
    ansible.builtin.debug:
      msg: "{{ fruits | split(',') }}"