- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle the undefine variable
    ansible.builtin.debug:
      msg: "Hello {{ person | default('Ramesh') }}"

  - name: converting string to list
    vars:
      fruits: "banana, apple, orange" #string
    ansible.builtin.debug:
      msg: "Fruits are: {{ fruits | split(',') }}"

  - name: converting map into list
    vars:
      course:
        name: "devops with aws"
        duration: 120HRS
        trainer: sivakumar
    ansible.builtin.debug:
      msg: "Course info: {{ course | dict2items }}"

  - name: converting list into map
    vars:
     course:
     -  {'key': 'name', 'value': 'devops with aws'}
     -  {'key': 'duration', 'value': '120HRS'}
     -  {'key': 'trainer', 'value': 'sivakumar'}
    ansible.builtin.debug:
      msg: "course info: {{ course | items2dict }}"

  - name: convert upper to lower
    vars:
      name: "BALA GURAVAIAH"
    ansible.builtin.debug:
      msg: "name is {{ name | lower }}"

  - name: convert upper to lower
    vars:
      name: "bala guravaiah"
    ansible.builtin.debug:
      msg: "name is {{ name | upper }}"

  - name: print the min and max
    vars:
      number: [3,30,25,245,43463]
    ansible.builtin.debug:
      msg: "min number is {{ number | min }}, max number is {{ number | max }}"