- name: create ec2 and route53 records
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-0e40ff3b0a56e2315
    sg_id: sg-08f49690bf42656e1
    ami_id: ami-09c813fb71547fc4f
    instance_type: t3.micro
    zone: daws82s.space
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: Install AWS Python libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - boto3
    - botocore

  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet_id: "{{ subnet_id }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      instance_type: "{{ instance_type }}"
    loop: "{{ instances }}"
    register: ec2_info

  # - name: print ec2 info
  #   ansible.builtin.debug:
  #     msg: "{{ ec2_info }}"

  - name: print private IP addresses
    ansible.builtin.debug:
      msg: "{{ item.item}}: {{ item.instances[0].private_ip_address }}"
    loop: "{{ ec2_info.results }}"

  - name: create private ip r53 records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}" 
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_info.results }}"

  - name: create public ip r53 record
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_info.results }}"
    when: item.item == "frontend"